villes = [
    {"id": 1, "nom": "Cotonou"},
    {"id": 2, "nom": "Porto-Novo"},
    {"id": 3, "nom": "Parakou"},
    {"id": 4, "nom": "Abomey"},
    {"id": 5, "nom": "Bohicon"},
    {"id": 6, "nom": "Natitingou"},
    {"id": 7, "nom": "Djougou"},
    {"id": 8, "nom": "Lokossa"},
    {"id": 9, "nom": "Ouidah"},
    {"id": 10, "nom": "Kandi"},
    {"id": 11, "nom": "Malanville"},
    {"id": 12, "nom": "Savalou"},
    {"id": 13, "nom": "Sakété"},
    {"id": 14, "nom": "Allada"},
    {"id": 15, "nom": "Aplahoué"},
    {"id": 16, "nom": "Comé"},
    {"id": 17, "nom": "Bembéréké"},
    {"id": 18, "nom": "Bassila"},
    {"id": 19, "nom": "Tchaourou"},
    {"id": 20, "nom": "Pobè"},
    {"id": 21, "nom": "Kérou"},
    {"id": 22, "nom": "Cové"},
    {"id": 23, "nom": "Nikki"},
    {"id": 24, "nom": "Banikoara"},
    {"id": 25, "nom": "Tanguiéta"},
]